enum ApiMethods {
    UserRegister = '/user/register',
    UserProfile = '/user/profile',
    UserChangePassword = '/user/password',
    UserLogout = '/session',
    UserLogin = '/session',
    UserAvatar = '/user/avatar',
    Movies = '/movies',
    LatestMovies = '/movies/latest',
    TopMovies = '/movies/top',
    FavouritesMovies = '/favourites',
    Rating = '/rating',
    Genres = '/genres',
    Countries = '/countries',
    Actors = '/actors',
    Directors = '/directors',
    TVShows = '/tvshows',
    Search = '/search',
    TopTVShows = '/tvshows/top',
    LatestTVShows = '/tvshows/latest',
    Content = '/content',
    Subscription = '/subscription',
}

export default ApiMethods;
