enum Events {
    PathChanged = 'pathChanged',
    RedirectBack = 'redirectBack',
    ProfileTabChanged = 'profileTabChanged',
    ContentInfoRequested = 'contentInfoRequested',
    RevealPopup = 'revealPopup',
    ContentInfoTabChanged = 'contentInfoTabChanged',
    InfoBlockClosed = 'infoBlockClosed',
    SubmitForm = 'submitForm',
    SubmitProfileForm = 'submitProfileForm',
    SignupUser = 'signupUser',
    LoginUser = 'loginUser',
    LogoutUser = 'logoutUser',
    UpdateProfileInfo = 'updateProfileInfo',
    UpdateProfileAvatar = 'updateProfileAvatar',
    UpdateUserProfile = 'updateUserProfile',
    UpdateUserInfo = 'updateUserInfo',
    UploadAvatar = 'uploadAvatar',
    VideoPlay = 'videoPlay',
    VideoPause = 'videoPause',
    Mute = 'mute',
    VolumeOn = 'volumeOn',
    FullscreenModeOn = 'fullscreenModeOn',
    FullscreenModeOff = 'fullscreenModeOff',
    UpdateHeader = 'updateHeader',
}

export default Events;
