name: Build and Delivery

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Install deps
        run: npm install

      - name: Build
        run: npm run build-prod

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: 188.166.99.23
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist"
          target: "/www/2020_2_Slash/"
